; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Alyasen CRM"
#define MyAppVersion "1.0.2"
#define MyAppPublisher "NOVA DEV."
#define MyAppURL "https://www.nova-dev-company.com/"
#define MyAppExeName "start.exe"
#define MyBuildRoot "."
#define MyDistDir MyBuildRoot + "\dist\start"
#define MyIconFile MyDistDir + "\_internal\resources\logo3.ico"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{1CDB15B3-06B3-409E-9D9A-8BE09690A044}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
UsePreviousAppDir=yes
UpdateUninstallLogAppName=yes

; Architecture settings
;ArchitecturesAllowed=x64compatible
;ArchitecturesInstallIn64BitMode=x64compatible

; Disable program group page (not needed)
DisableProgramGroupPage=yes

; Output setup file name
OutputBaseFilename=alyasen-setup/Alyasen_Setup_{#MyAppVersion}

SetupIconFile={#MyIconFile}

; Compression
SolidCompression=yes
Compression=lzma2/ultra64

; Wizard style
WizardStyle=modern

; --- Auto-Update Support ---
; Close running application before installing update
CloseApplications=yes
CloseApplicationsFilter={#MyAppExeName}
RestartApplications=yes

[Languages]
;Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyDistDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyDistDir}\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MyBuildRoot}\.env"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
